#pragma once

#define OVERPLUS_VER_MAJOR 1
#define OVERPLUS_VER_MINOR 0
#define OVERPLUS_VER_PATCH 5

#define OVERPLUS_VERSION (OVERPLUS_VER_MAJOR * 10000 + OVERPLUS_VER_MINOR * 100 + OVERPLUS_VER_PATCH)
const char* OVERPLUS_VERSION_STR ="v1.0.5";

